service: serverless-runtime
useDotenv: true
plugins:
- serverless-offline
- serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  stage: dev
  region: us-east-1

functions:
  main:
    handler: dist/main.handler
    events:
    - http:
        method: any
        path: /
    - http:
        method: any
        path: /{proxy+}

