service: serverless-runtime
useDotenv: true
plugins:
- serverless-offline
- serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DATABASE_URL: ${env:DATABASE_URL}
  stage: dev
  region: us-east-1
functions:
  main:
    handler: dist/main.handler
    events:
    - http:
        method: any
        path: /
    - http:
        method: any
        path: /{proxy+}
    - http:
        method: any
        path: /v1/health
        cors: true
    - http:
        method: POST
        path: /v1/products/crated
    - http:
        method: GET
        path: /v1/products
    - http:
        method: PUT
        path: /v1/products/sales/{id}

